# Generated by Django 5.2.17 on 2026-08-30 02:56

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grocery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_identity", models.CharField(max_length=512)),
                (
                    "ordered_manifest_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("page_count", models.PositiveIntegerField()),
                ("total_bytes", models.PositiveBigIntegerField()),
                (
                    "media_type",
                    models.CharField(
                        choices=[("application/json", "JSON")],
                        default="application/json",
                        max_length=32,
                    ),
                ),
                (
                    "encoding",
                    models.CharField(choices=[("utf-8", "UTF-8")], default="utf-8", max_length=16),
                ),
                (
                    "retention_mode",
                    models.CharField(
                        choices=[("HASH_ONLY", "Hash only")], default="HASH_ONLY", max_length=16
                    ),
                ),
                ("first_seen_at", models.DateTimeField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_identity", "ordered_manifest_sha256"),
                        name="grocery_artifact_source_manifest_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_identity", ""), _negated=True),
                        name="grocery_artifact_source_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ordered_manifest_sha256__regex", "^[0-9a-f]{64}$")),
                        name="grocery_artifact_manifest_hash_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("page_count__gt", 0)),
                        name="grocery_artifact_page_count_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("total_bytes__gte", 0)),
                        name="grocery_artifact_bytes_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("media_type", "application/json")),
                        name="grocery_artifact_media_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("encoding", "utf-8")),
                        name="grocery_artifact_encoding_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("retention_mode", "HASH_ONLY")),
                        name="grocery_artifact_retention_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ParseRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("parser_revision", models.CharField(max_length=64)),
                (
                    "configuration_hash",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "result_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("VALIDATED", "Validated"),
                            ("QUARANTINED", "Quarantined"),
                            ("FAILED", "Failed"),
                        ],
                        default="STARTED",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_row_count", models.PositiveIntegerField(default=0)),
                ("accepted_row_count", models.PositiveIntegerField(default=0)),
                ("missing_reference_row_count", models.PositiveIntegerField(default=0)),
                ("out_of_scope_row_count", models.PositiveIntegerField(default=0)),
                ("quarantined_row_count", models.PositiveIntegerField(default=0)),
                (
                    "failure_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        validators=[django.core.validators.RegexValidator("^[A-Z][A-Z0-9_]*$")],
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parse_runs",
                        to="grocery.sourceartifact",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fetchattempt",
            name="artifact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fetch_attempts",
                to="grocery.sourceartifact",
            ),
        ),
        migrations.AddConstraint(
            model_name="fetchattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("artifact__isnull", True), ("state", "SUCCEEDED"), _connector="OR"
                ),
                name="grocery_fetch_artifact_success_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="parserun",
            constraint=models.UniqueConstraint(
                fields=("artifact", "parser_revision", "configuration_hash"),
                name="grocery_parse_artifact_revision_config_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="parserun",
            constraint=models.CheckConstraint(
                condition=models.Q(("parser_revision", ""), _negated=True),
                name="grocery_parse_revision_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="parserun",
            constraint=models.CheckConstraint(
                condition=models.Q(("configuration_hash__regex", "^[0-9a-f]{64}$")),
                name="grocery_parse_configuration_hash_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="parserun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("result_hash", ""), ("result_hash__regex", "^[0-9a-f]{64}$"), _connector="OR"
                ),
                name="grocery_parse_result_hash_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="parserun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("STARTED", "VALIDATED", "QUARANTINED", "FAILED"))
                ),
                name="grocery_parse_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="parserun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_row_count__gte", 0),
                    ("accepted_row_count__gte", 0),
                    ("missing_reference_row_count__gte", 0),
                    ("out_of_scope_row_count__gte", 0),
                    ("quarantined_row_count__gte", 0),
                ),
                name="grocery_parse_counts_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="parserun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_row_count",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("accepted_row_count"),
                                "+",
                                models.F("out_of_scope_row_count"),
                            ),
                            "+",
                            models.F("quarantined_row_count"),
                        ),
                    )
                ),
                name="grocery_parse_total_reconciled",
            ),
        ),
        migrations.AddConstraint(
            model_name="parserun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("missing_reference_row_count__lte", models.F("accepted_row_count"))
                ),
                name="grocery_parse_missing_within_accepted",
            ),
        ),
        migrations.AddConstraint(
            model_name="parserun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("failure_code", ""),
                    ("failure_code__regex", "^[A-Z][A-Z0-9_]*$"),
                    _connector="OR",
                ),
                name="grocery_parse_failure_code_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="parserun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", True),
                        ("failure_code", ""),
                        ("result_hash", ""),
                        ("status", "STARTED"),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("failure_code", ""),
                        ("quarantined_row_count", 0),
                        ("status", "VALIDATED"),
                        models.Q(("result_hash", ""), _negated=True),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("quarantined_row_count__gt", 0),
                        ("result_hash", ""),
                        ("status", "QUARANTINED"),
                        models.Q(("failure_code", ""), _negated=True),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("result_hash", ""),
                        ("status", "FAILED"),
                        models.Q(("failure_code", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="grocery_parse_status_outcome_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="parserun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completed_at__isnull", True),
                    ("completed_at__gte", models.F("started_at")),
                    _connector="OR",
                ),
                name="grocery_parse_time_order_valid",
            ),
        ),
    ]
