# Generated by Django 5.2.17 on 2026-08-30 03:13

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

IMMUTABLE_TRIGGER_SQL = """
CREATE FUNCTION grocery_retailpricesnapshot_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    RAISE EXCEPTION 'grocery_retailpricesnapshot rows are immutable'
        USING ERRCODE = '55000';
END;
$function$;

CREATE TRIGGER grocery_retailpricesnapshot_immutable
BEFORE UPDATE OR DELETE ON grocery_retailpricesnapshot
FOR EACH ROW
EXECUTE FUNCTION grocery_retailpricesnapshot_reject_mutation();
"""

DROP_IMMUTABLE_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS grocery_retailpricesnapshot_immutable
    ON grocery_retailpricesnapshot;
DROP FUNCTION IF EXISTS grocery_retailpricesnapshot_reject_mutation();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("grocery", "0003_price_series_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailPriceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_effective_date", models.DateField()),
                ("source_recorded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("KRW", "South Korean won")], default="KRW", max_length=3
                    ),
                ),
                (
                    "source_row_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("source_contract_revision", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parse_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_price_snapshots",
                        to="grocery.parserun",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_price_snapshots",
                        to="grocery.priceserieskey",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parse_run", "series", "source_effective_date"),
                        name="grocery_snapshot_run_series_date_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("parse_run", "series"), name="grocery_snapshot_run_series_uniq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("current_price__gt", 0)),
                        name="grocery_snapshot_price_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency", "KRW")),
                        name="grocery_snapshot_currency_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_row_sha256__regex", "^[0-9a-f]{64}$")),
                        name="grocery_snapshot_row_hash_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_contract_revision", ""), _negated=True),
                        name="grocery_snapshot_contract_nonempty",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql=IMMUTABLE_TRIGGER_SQL,
            reverse_sql=DROP_IMMUTABLE_TRIGGER_SQL,
        ),
    ]
