# Generated by Django 5.2.17 on 2026-08-30

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

TRIGGER_SQL = """
CREATE FUNCTION grocery_referenceprice_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    RAISE EXCEPTION 'grocery_referenceprice rows are immutable'
        USING ERRCODE = '55000';
END;
$function$;

CREATE TRIGGER grocery_referenceprice_immutable
BEFORE UPDATE OR DELETE ON grocery_referenceprice
FOR EACH ROW
EXECUTE FUNCTION grocery_referenceprice_reject_mutation();

CREATE FUNCTION grocery_pricechangefact_validate_values()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    current_value numeric;
    reference_value numeric;
    reference_status text;
    expected_difference numeric;
    expected_percentage numeric;
    expected_direction text;
BEGIN
    SELECT snapshot.current_price, reference.value, reference.value_status
      INTO current_value, reference_value, reference_status
      FROM grocery_referenceprice AS reference
      JOIN grocery_retailpricesnapshot AS snapshot
        ON snapshot.id = reference.snapshot_id
     WHERE reference.id = NEW.reference_price_id;

    IF NOT FOUND THEN
        RETURN NEW;
    END IF;

    IF reference_status = 'UNAVAILABLE' THEN
        IF NEW.direction IS DISTINCT FROM 'UNAVAILABLE'
           OR NEW.signed_difference IS NOT NULL
           OR NEW.signed_percentage IS NOT NULL THEN
            RAISE EXCEPTION 'price change does not match unavailable reference state'
                USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
    END IF;

    expected_difference := current_value - reference_value;
    expected_percentage := round((expected_difference / reference_value) * 100, 1);
    expected_direction := CASE
        WHEN expected_difference < 0 THEN 'LOWER'
        WHEN expected_difference > 0 THEN 'HIGHER'
        ELSE 'EQUAL'
    END;

    IF NEW.direction IS DISTINCT FROM expected_direction
       OR NEW.signed_difference IS DISTINCT FROM expected_difference
       OR NEW.signed_percentage IS DISTINCT FROM expected_percentage THEN
        RAISE EXCEPTION 'price change does not match deterministic calculation'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$function$;

CREATE TRIGGER grocery_pricechangefact_validate
BEFORE INSERT ON grocery_pricechangefact
FOR EACH ROW
EXECUTE FUNCTION grocery_pricechangefact_validate_values();

CREATE FUNCTION grocery_pricechangefact_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    RAISE EXCEPTION 'grocery_pricechangefact rows are immutable'
        USING ERRCODE = '55000';
END;
$function$;

CREATE TRIGGER grocery_pricechangefact_immutable
BEFORE UPDATE OR DELETE ON grocery_pricechangefact
FOR EACH ROW
EXECUTE FUNCTION grocery_pricechangefact_reject_mutation();
"""

DROP_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS grocery_pricechangefact_immutable
    ON grocery_pricechangefact;
DROP FUNCTION IF EXISTS grocery_pricechangefact_reject_mutation();
DROP TRIGGER IF EXISTS grocery_pricechangefact_validate
    ON grocery_pricechangefact;
DROP FUNCTION IF EXISTS grocery_pricechangefact_validate_values();
DROP TRIGGER IF EXISTS grocery_referenceprice_immutable
    ON grocery_referenceprice;
DROP FUNCTION IF EXISTS grocery_referenceprice_reject_mutation();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("grocery", "0004_retail_price_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferencePrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("WEEK", "One week"),
                            ("MONTH", "One month"),
                            ("YEAR", "One year"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "value_status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                    ),
                ),
                (
                    "unavailable_reason",
                    models.CharField(
                        blank=True,
                        choices=[("SOURCE_VALUE_MISSING", "Source value missing")],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "reference_date_status",
                    models.CharField(
                        choices=[
                            (
                                "SOURCE_REFERENCE_DATE_UNAVAILABLE",
                                "Source reference date unavailable",
                            )
                        ],
                        default="SOURCE_REFERENCE_DATE_UNAVAILABLE",
                        max_length=40,
                    ),
                ),
                ("source_reference_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reference_prices",
                        to="grocery.retailpricesnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceChangeFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("LOWER", "Lower"),
                            ("EQUAL", "Equal"),
                            ("HIGHER", "Higher"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "signed_difference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "signed_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=16,
                        null=True,
                    ),
                ),
                (
                    "calculation_revision",
                    models.CharField(
                        default="PRICE_COMPARISON_V1",
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "rounding_mode",
                    models.CharField(
                        choices=[("ROUND_HALF_UP", "Round half up")],
                        default="ROUND_HALF_UP",
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_price",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_fact",
                        to="grocery.referenceprice",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="referenceprice",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "period"),
                name="grocery_reference_snapshot_period_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="referenceprice",
            constraint=models.CheckConstraint(
                condition=models.Q(("period__in", ("WEEK", "MONTH", "YEAR"))),
                name="grocery_reference_period_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="referenceprice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("unavailable_reason__isnull", True),
                        ("value__isnull", False),
                        ("value_status", "AVAILABLE"),
                        ("value__gt", 0),
                    ),
                    models.Q(
                        ("unavailable_reason", "SOURCE_VALUE_MISSING"),
                        ("unavailable_reason__isnull", False),
                        ("value__isnull", True),
                        ("value_status", "UNAVAILABLE"),
                    ),
                    _connector="OR",
                ),
                name="grocery_reference_value_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="referenceprice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reference_date_status", "SOURCE_REFERENCE_DATE_UNAVAILABLE"),
                    ("source_reference_date__isnull", True),
                ),
                name="grocery_reference_date_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricechangefact",
            constraint=models.CheckConstraint(
                condition=models.Q(("direction__in", ("LOWER", "EQUAL", "HIGHER", "UNAVAILABLE"))),
                name="grocery_change_direction_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricechangefact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("direction", "UNAVAILABLE"),
                        ("signed_difference__isnull", True),
                        ("signed_percentage__isnull", True),
                    ),
                    models.Q(
                        ("signed_difference__isnull", False),
                        ("signed_percentage__isnull", False),
                        models.Q(
                            models.Q(("direction", "LOWER"), ("signed_difference__lt", 0)),
                            models.Q(("direction", "EQUAL"), ("signed_difference", 0)),
                            models.Q(("direction", "HIGHER"), ("signed_difference__gt", 0)),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="grocery_change_value_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricechangefact",
            constraint=models.CheckConstraint(
                condition=models.Q(("calculation_revision", "PRICE_COMPARISON_V1")),
                name="grocery_change_revision_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricechangefact",
            constraint=models.CheckConstraint(
                condition=models.Q(("rounding_mode", "ROUND_HALF_UP")),
                name="grocery_change_rounding_valid",
            ),
        ),
        migrations.RunSQL(sql=TRIGGER_SQL, reverse_sql=DROP_TRIGGER_SQL),
    ]
