# Generated by Django 5.2.17 on 2026-08-30 03:36

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

VALIDATE_AND_IMMUTABLE_SQL = """
CREATE FUNCTION grocery_reviewdecision_validate_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    source_record grocery_sourceconfiguration%ROWTYPE;
    parse_record grocery_parserun%ROWTYPE;
    superseded_record grocery_reviewdecision%ROWTYPE;
    snapshot_count bigint;
    invalid_snapshot_count bigint;
BEGIN
    SELECT * INTO source_record
      FROM grocery_sourceconfiguration
     WHERE id = NEW.source_configuration_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'review source configuration does not exist'
            USING ERRCODE = '23514';
    END IF;

    IF source_record.state IS DISTINCT FROM 'ACTIVE'
       OR source_record.rights_evidence_locator = ''
       OR source_record.rights_evidence_sha256 = ''
       OR source_record.rights_confirmed_at IS NULL THEN
        RAISE EXCEPTION 'review requires active source and complete rights evidence'
            USING ERRCODE = '23514';
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM grocery_fetchattempt
         WHERE source_configuration_id = NEW.source_configuration_id
           AND artifact_id = NEW.source_artifact_id
           AND state = 'SUCCEEDED'
    ) THEN
        RAISE EXCEPTION 'review artifact is not linked by a succeeded fetch attempt'
            USING ERRCODE = '23514';
    END IF;

    SELECT * INTO parse_record
      FROM grocery_parserun
     WHERE id = NEW.parse_run_id;
    IF NOT FOUND OR parse_record.artifact_id IS DISTINCT FROM NEW.source_artifact_id THEN
        RAISE EXCEPTION 'review parse run and artifact do not match'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.supersedes_id IS NOT NULL THEN
        IF NEW.supersedes_id = NEW.id THEN
            RAISE EXCEPTION 'review decision cannot supersede itself'
                USING ERRCODE = '23514';
        END IF;
        SELECT * INTO superseded_record
          FROM grocery_reviewdecision
         WHERE id = NEW.supersedes_id
         FOR UPDATE;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'superseded review decision does not exist'
                USING ERRCODE = '23514';
        END IF;
        IF superseded_record.source_configuration_id IS DISTINCT FROM NEW.source_configuration_id
           OR superseded_record.source_artifact_id IS DISTINCT FROM NEW.source_artifact_id
           OR superseded_record.parse_run_id IS DISTINCT FROM NEW.parse_run_id THEN
            RAISE EXCEPTION 'review decision can only supersede the same generation'
                USING ERRCODE = '23514';
        END IF;
        IF EXISTS (
            SELECT 1
              FROM grocery_reviewdecision
             WHERE supersedes_id = NEW.supersedes_id
        ) THEN
            RAISE EXCEPTION 'only the current review tail can be superseded'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    IF NEW.decision = 'REJECT' THEN
        IF parse_record.status = 'STARTED' OR parse_record.completed_at IS NULL THEN
            RAISE EXCEPTION 'rejected review requires a completed parse run'
                USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
    END IF;

    IF parse_record.status IS DISTINCT FROM 'VALIDATED'
       OR parse_record.completed_at IS NULL
       OR parse_record.result_hash = ''
       OR parse_record.quarantined_row_count <> 0 THEN
        RAISE EXCEPTION 'approved review requires a validated reconciled parse run'
            USING ERRCODE = '23514';
    END IF;

    IF source_record.publication_mode IS DISTINCT FROM 'RECENT_COMPARISON'
       OR NEW.approved_mode IS DISTINCT FROM source_record.publication_mode
       OR NEW.approved_coverage_identity IS DISTINCT FROM source_record.coverage_identity
       OR NEW.approved_coverage_evidence_revision
          IS DISTINCT FROM source_record.coverage_evidence_revision THEN
        RAISE EXCEPTION 'approved mode and coverage do not match source configuration'
            USING ERRCODE = '23514';
    END IF;

    SELECT count(*) INTO snapshot_count
      FROM grocery_retailpricesnapshot
     WHERE parse_run_id = NEW.parse_run_id;
    IF snapshot_count IS DISTINCT FROM parse_record.accepted_row_count::bigint THEN
        RAISE EXCEPTION 'snapshot count does not match accepted row count'
            USING ERRCODE = '23514';
    END IF;

    SELECT count(*) INTO invalid_snapshot_count
      FROM (
        SELECT snapshot.id
          FROM grocery_retailpricesnapshot AS snapshot
          LEFT JOIN grocery_referenceprice AS reference
            ON reference.snapshot_id = snapshot.id
          LEFT JOIN grocery_pricechangefact AS change_fact
            ON change_fact.reference_price_id = reference.id
         WHERE snapshot.parse_run_id = NEW.parse_run_id
         GROUP BY snapshot.id
        HAVING count(reference.id) <> 3
            OR count(DISTINCT reference.period) <> 3
            OR count(change_fact.id) <> 3
      ) AS invalid_snapshot;
    IF invalid_snapshot_count <> 0 THEN
        RAISE EXCEPTION 'approved snapshots require exact reference and change facts'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$function$;

CREATE TRIGGER grocery_reviewdecision_validate
BEFORE INSERT ON grocery_reviewdecision
FOR EACH ROW
EXECUTE FUNCTION grocery_reviewdecision_validate_insert();

CREATE FUNCTION grocery_reviewdecision_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    RAISE EXCEPTION 'grocery_reviewdecision rows are append-only'
        USING ERRCODE = '55000';
END;
$function$;

CREATE TRIGGER grocery_reviewdecision_immutable
BEFORE UPDATE OR DELETE ON grocery_reviewdecision
FOR EACH ROW
EXECUTE FUNCTION grocery_reviewdecision_reject_mutation();
"""

DROP_VALIDATE_AND_IMMUTABLE_SQL = """
DROP TRIGGER IF EXISTS grocery_reviewdecision_immutable
    ON grocery_reviewdecision;
DROP FUNCTION IF EXISTS grocery_reviewdecision_reject_mutation();
DROP TRIGGER IF EXISTS grocery_reviewdecision_validate
    ON grocery_reviewdecision;
DROP FUNCTION IF EXISTS grocery_reviewdecision_validate_insert();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("grocery", "0005_reference_price_change_facts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("APPROVE", "Approve"), ("REJECT", "Reject")],
                        max_length=8,
                    ),
                ),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "reconciliation_report_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "acceptance_evidence_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        max_length=64,
                        validators=[django.core.validators.RegexValidator("^[A-Z][A-Z0-9_]*$")],
                    ),
                ),
                (
                    "approved_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RECENT_COMPARISON", "Recent comparison"),
                            ("CURRENT_ONLY", "Current only"),
                            ("STATIC_MONTHLY_FILE", "Static monthly file"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "approved_coverage_identity",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "approved_coverage_evidence_revision",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "parse_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_decisions",
                        to="grocery.parserun",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grocery_review_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_decisions",
                        to="grocery.sourceartifact",
                    ),
                ),
                (
                    "source_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_decisions",
                        to="grocery.sourceconfiguration",
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseding_decision",
                        to="grocery.reviewdecision",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("review_generation", "Can review a parsed grocery source generation")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("decision__in", ("APPROVE", "REJECT"))),
                        name="grocery_review_decision_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reconciliation_report_sha256__regex", "^[0-9a-f]{64}$")
                        ),
                        name="grocery_review_report_hash_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("acceptance_evidence_sha256__regex", "^[0-9a-f]{64}$")),
                        name="grocery_review_acceptance_hash_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason_code__regex", "^[A-Z][A-Z0-9_]*$")),
                        name="grocery_review_reason_code_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("approved_mode", "RECENT_COMPARISON"),
                                ("decision", "APPROVE"),
                                models.Q(("approved_coverage_identity", ""), _negated=True),
                                models.Q(
                                    ("approved_coverage_evidence_revision", ""),
                                    _negated=True,
                                ),
                            ),
                            models.Q(
                                ("approved_coverage_evidence_revision", ""),
                                ("approved_coverage_identity", ""),
                                ("approved_mode", ""),
                                ("decision", "REJECT"),
                            ),
                            _connector="OR",
                        ),
                        name="grocery_review_approval_fields_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("supersedes__isnull", True),
                            models.Q(("id", models.F("supersedes_id")), _negated=True),
                            _connector="OR",
                        ),
                        name="grocery_review_not_self_supersede",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("supersedes__isnull", True)),
                        fields=("source_configuration", "source_artifact", "parse_run"),
                        name="grocery_review_generation_root_uniq",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql=VALIDATE_AND_IMMUTABLE_SQL,
            reverse_sql=DROP_VALIDATE_AND_IMMUTABLE_SQL,
        ),
    ]
