# Generated by Django 5.2.17 on 2026-08-30

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

PUBLICATION_TRIGGER_SQL = r"""
CREATE FUNCTION grocery_publicationrevision_validate_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.sealed_at IS NOT NULL THEN
        RAISE EXCEPTION 'publication revisions must be inserted unsealed'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$function$;

CREATE TRIGGER grocery_publicationrevision_unsealed_insert
BEFORE INSERT ON grocery_publicationrevision
FOR EACH ROW
EXECUTE FUNCTION grocery_publicationrevision_validate_insert();

CREATE FUNCTION grocery_publication_snapshot_fact_sha256(snapshot_pk uuid)
RETURNS text
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    reference_json text;
    canonical_json text;
BEGIN
    SELECT string_agg(
               '{'
               || '"change":{'
               || '"calculation_revision":' || to_json(change_fact.calculation_revision)::text
               || ',"direction":' || to_json(change_fact.direction)::text
               || ',"rounding_mode":' || to_json(change_fact.rounding_mode)::text
               || ',"signed_difference":'
               || CASE
                      WHEN change_fact.signed_difference IS NULL THEN 'null'
                      ELSE to_json(change_fact.signed_difference::text)::text
                  END
               || ',"signed_percentage":'
               || CASE
                      WHEN change_fact.signed_percentage IS NULL THEN 'null'
                      ELSE to_json(change_fact.signed_percentage::text)::text
                  END
               || '}'
               || ',"period":' || to_json(reference.period)::text
               || ',"reference_date_status":' || to_json(reference.reference_date_status)::text
               || ',"source_reference_date":'
               || CASE
                      WHEN reference.source_reference_date IS NULL THEN 'null'
                      ELSE to_json(reference.source_reference_date::text)::text
                  END
               || ',"unavailable_reason":'
               || CASE
                      WHEN reference.unavailable_reason IS NULL THEN 'null'
                      ELSE to_json(reference.unavailable_reason)::text
                  END
               || ',"value":'
               || CASE
                      WHEN reference.value IS NULL THEN 'null'
                      ELSE to_json(reference.value::text)::text
                  END
               || ',"value_status":' || to_json(reference.value_status)::text
               || '}',
               ',' ORDER BY CASE reference.period
                   WHEN 'WEEK' THEN 1
                   WHEN 'MONTH' THEN 2
                   WHEN 'YEAR' THEN 3
                   ELSE 4
               END
           )
      INTO reference_json
      FROM grocery_referenceprice AS reference
      JOIN grocery_pricechangefact AS change_fact
        ON change_fact.reference_price_id = reference.id
     WHERE reference.snapshot_id = snapshot_pk;

    SELECT '{'
           || '"entry_hash_version":'
           || to_json('recent-retail-entry-v1'::text)::text
           || ',"references":[' || reference_json || ']'
           || ',"series":{'
           || '"category_code":' || to_json(series.category_code)::text
           || ',"category_name":' || to_json(series.category_name)::text
           || ',"coverage_identity":' || to_json(series.coverage_identity)::text
           || ',"grade_code":' || to_json(series.grade_code)::text
           || ',"grade_name":' || to_json(series.grade_name)::text
           || ',"identity_evidence_revision":'
           || to_json(series.identity_evidence_revision)::text
           || ',"item_code":' || to_json(series.item_code)::text
           || ',"item_name":' || to_json(series.item_name)::text
           || ',"product_class_code":' || to_json(series.product_class_code)::text
           || ',"product_class_name":' || to_json(series.product_class_name)::text
           || ',"raw_unit":' || to_json(series.raw_unit)::text
           || ',"raw_unit_size":' || to_json(series.raw_unit_size)::text
           || ',"variety_code":' || to_json(series.variety_code)::text
           || ',"variety_name":' || to_json(series.variety_name)::text
           || '}'
           || ',"snapshot":{'
           || '"currency":' || to_json(snapshot.currency)::text
           || ',"current_price":' || to_json(snapshot.current_price::text)::text
           || ',"source_contract_revision":'
           || to_json(snapshot.source_contract_revision)::text
           || ',"source_effective_date":'
           || to_json(snapshot.source_effective_date::text)::text
           || ',"source_recorded_at":'
           || CASE
                  WHEN snapshot.source_recorded_at IS NULL THEN 'null'
                  ELSE to_json(
                      to_char(
                          snapshot.source_recorded_at AT TIME ZONE 'UTC',
                          'YYYY-MM-DD"T"HH24:MI:SS'
                      )
                      || CASE
                             WHEN extract(microseconds FROM snapshot.source_recorded_at)::integer
                                  % 1000000 = 0 THEN ''
                             ELSE '.' || to_char(
                                 snapshot.source_recorded_at AT TIME ZONE 'UTC',
                                 'US'
                             )
                         END
                      || '+00:00'
                  )::text
              END
           || ',"source_row_sha256":' || to_json(snapshot.source_row_sha256)::text
           || '}'
           || '}'
      INTO canonical_json
      FROM grocery_retailpricesnapshot AS snapshot
      JOIN grocery_priceserieskey AS series
        ON series.id = snapshot.series_id
     WHERE snapshot.id = snapshot_pk;

    IF canonical_json IS NULL OR reference_json IS NULL THEN
        RETURN NULL;
    END IF;
    RETURN encode(
        sha256(convert_to('recent-retail-entry-v1' || E'\n' || canonical_json, 'UTF8')),
        'hex'
    );
END;
$function$;

CREATE FUNCTION grocery_publicationentry_validate_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    revision_generation uuid;
    revision_sealed_at timestamptz;
    snapshot_generation uuid;
    actual_fact_sha256 text;
BEGIN
    SELECT generation_id, sealed_at
      INTO revision_generation, revision_sealed_at
      FROM grocery_publicationrevision
     WHERE id = NEW.revision_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'publication revision does not exist'
            USING ERRCODE = '23514';
    END IF;
    IF revision_sealed_at IS NOT NULL THEN
        RAISE EXCEPTION 'publication entries can only be inserted while unsealed'
            USING ERRCODE = '55000';
    END IF;

    SELECT parse_run_id
      INTO snapshot_generation
      FROM grocery_retailpricesnapshot
     WHERE id = NEW.snapshot_id;
    IF NOT FOUND OR snapshot_generation IS DISTINCT FROM revision_generation THEN
        RAISE EXCEPTION 'publication entry snapshot does not match revision generation'
            USING ERRCODE = '23514';
    END IF;
    actual_fact_sha256 := grocery_publication_snapshot_fact_sha256(NEW.snapshot_id);
    IF actual_fact_sha256 IS NULL
       OR actual_fact_sha256 IS DISTINCT FROM NEW.fact_sha256 THEN
        RAISE EXCEPTION 'publication entry hash does not match canonical snapshot facts'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$function$;

CREATE TRIGGER grocery_publicationentry_validate
BEFORE INSERT ON grocery_publicationentry
FOR EACH ROW
EXECUTE FUNCTION grocery_publicationentry_validate_insert();

CREATE FUNCTION grocery_publicationentry_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    RAISE EXCEPTION 'grocery_publicationentry rows are immutable'
        USING ERRCODE = '55000';
END;
$function$;

CREATE TRIGGER grocery_publicationentry_immutable
BEFORE UPDATE OR DELETE ON grocery_publicationentry
FOR EACH ROW
EXECUTE FUNCTION grocery_publicationentry_reject_mutation();

CREATE FUNCTION grocery_publicationrevision_validate_seal()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    decision_record grocery_reviewdecision%ROWTYPE;
    generation_record grocery_parserun%ROWTYPE;
    source_record grocery_sourceconfiguration%ROWTYPE;
    generation_snapshot_count bigint;
    entry_total bigint;
    entry_snapshot_total bigint;
    ordinal_total bigint;
    ordinal_min integer;
    ordinal_max integer;
    invalid_generation_count bigint;
    invalid_coverage_count bigint;
    actual_date_min date;
    actual_date_max date;
    actual_fact_set_sha256 text;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'grocery_publicationrevision rows are immutable'
            USING ERRCODE = '55000';
    END IF;

    IF OLD.sealed_at IS NOT NULL OR NEW.sealed_at IS NULL
       OR NEW.id IS DISTINCT FROM OLD.id
       OR NEW.channel IS DISTINCT FROM OLD.channel
       OR NEW.mode IS DISTINCT FROM OLD.mode
       OR NEW.review_decision_id IS DISTINCT FROM OLD.review_decision_id
       OR NEW.generation_id IS DISTINCT FROM OLD.generation_id
       OR NEW.parser_revision IS DISTINCT FROM OLD.parser_revision
       OR NEW.fact_hash_version IS DISTINCT FROM OLD.fact_hash_version
       OR NEW.typed_fact_set_sha256 IS DISTINCT FROM OLD.typed_fact_set_sha256
       OR NEW.entry_count IS DISTINCT FROM OLD.entry_count
       OR NEW.source_effective_date_min IS DISTINCT FROM OLD.source_effective_date_min
       OR NEW.source_effective_date_max IS DISTINCT FROM OLD.source_effective_date_max
       OR NEW.public_copy_revision IS DISTINCT FROM OLD.public_copy_revision
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'publication revision only allows a one-time seal transition'
            USING ERRCODE = '55000';
    END IF;

    SELECT * INTO decision_record
      FROM grocery_reviewdecision
     WHERE id = NEW.review_decision_id;
    IF NOT FOUND
       OR decision_record.decision IS DISTINCT FROM 'APPROVE'
       OR decision_record.parse_run_id IS DISTINCT FROM NEW.generation_id
       OR decision_record.approved_mode IS DISTINCT FROM NEW.mode THEN
        RAISE EXCEPTION 'publication seal requires the matching approved review decision'
            USING ERRCODE = '23514';
    END IF;
    IF EXISTS (
        SELECT 1
          FROM grocery_reviewdecision
         WHERE supersedes_id = decision_record.id
    ) THEN
        RAISE EXCEPTION 'publication seal requires the latest review decision tail'
            USING ERRCODE = '23514';
    END IF;

    SELECT * INTO generation_record
      FROM grocery_parserun
     WHERE id = NEW.generation_id;
    IF NOT FOUND
       OR generation_record.status IS DISTINCT FROM 'VALIDATED'
       OR generation_record.parser_revision IS DISTINCT FROM NEW.parser_revision
       OR generation_record.accepted_row_count IS DISTINCT FROM NEW.entry_count THEN
        RAISE EXCEPTION 'publication generation, parser, and accepted count do not match'
            USING ERRCODE = '23514';
    END IF;

    SELECT * INTO source_record
      FROM grocery_sourceconfiguration
     WHERE id = decision_record.source_configuration_id;
    IF NOT FOUND
       OR NEW.channel IS DISTINCT FROM 'RECENT_RETAIL'
       OR NEW.mode IS DISTINCT FROM 'RECENT_COMPARISON'
       OR source_record.publication_mode IS DISTINCT FROM NEW.mode
       OR decision_record.approved_coverage_identity
          IS DISTINCT FROM source_record.coverage_identity
       OR decision_record.approved_coverage_evidence_revision
          IS DISTINCT FROM source_record.coverage_evidence_revision THEN
        RAISE EXCEPTION 'publication mode and coverage do not match the approved source'
            USING ERRCODE = '23514';
    END IF;

    SELECT count(*) INTO generation_snapshot_count
      FROM grocery_retailpricesnapshot
     WHERE parse_run_id = NEW.generation_id;
    IF generation_snapshot_count IS DISTINCT FROM NEW.entry_count::bigint THEN
        RAISE EXCEPTION 'publication generation snapshot count does not match entry count'
            USING ERRCODE = '23514';
    END IF;

    SELECT count(*),
           count(DISTINCT snapshot_id),
           count(DISTINCT ordinal),
           min(ordinal),
           max(ordinal)
      INTO entry_total,
           entry_snapshot_total,
           ordinal_total,
           ordinal_min,
           ordinal_max
      FROM grocery_publicationentry
     WHERE revision_id = NEW.id;
    IF entry_total IS DISTINCT FROM NEW.entry_count::bigint
       OR entry_snapshot_total IS DISTINCT FROM NEW.entry_count::bigint
       OR ordinal_total IS DISTINCT FROM NEW.entry_count::bigint
       OR ordinal_min IS DISTINCT FROM 1
       OR ordinal_max IS DISTINCT FROM NEW.entry_count THEN
        RAISE EXCEPTION 'publication entries must be complete, distinct, and contiguous'
            USING ERRCODE = '23514';
    END IF;

    SELECT count(*) INTO invalid_generation_count
      FROM grocery_publicationentry AS entry
      JOIN grocery_retailpricesnapshot AS snapshot
        ON snapshot.id = entry.snapshot_id
     WHERE entry.revision_id = NEW.id
       AND snapshot.parse_run_id IS DISTINCT FROM NEW.generation_id;
    IF invalid_generation_count <> 0 THEN
        RAISE EXCEPTION 'publication entries contain a mixed generation'
            USING ERRCODE = '23514';
    END IF;

    SELECT count(*) INTO invalid_coverage_count
      FROM grocery_publicationentry AS entry
      JOIN grocery_retailpricesnapshot AS snapshot
        ON snapshot.id = entry.snapshot_id
      JOIN grocery_priceserieskey AS series
        ON series.id = snapshot.series_id
     WHERE entry.revision_id = NEW.id
       AND series.coverage_identity
           IS DISTINCT FROM decision_record.approved_coverage_identity;
    IF invalid_coverage_count <> 0 THEN
        RAISE EXCEPTION 'publication entries contain unapproved coverage'
            USING ERRCODE = '23514';
    END IF;

    SELECT min(snapshot.source_effective_date), max(snapshot.source_effective_date)
      INTO actual_date_min, actual_date_max
      FROM grocery_publicationentry AS entry
      JOIN grocery_retailpricesnapshot AS snapshot
        ON snapshot.id = entry.snapshot_id
     WHERE entry.revision_id = NEW.id;
    IF actual_date_min IS DISTINCT FROM NEW.source_effective_date_min
       OR actual_date_max IS DISTINCT FROM NEW.source_effective_date_max THEN
        RAISE EXCEPTION 'publication source effective date range does not match membership'
            USING ERRCODE = '23514';
    END IF;

    SELECT encode(
               sha256(
                   convert_to(
                       NEW.fact_hash_version || E'\n'
                       || string_agg(entry.fact_sha256, E'\n' ORDER BY entry.ordinal),
                       'UTF8'
                   )
               ),
               'hex'
           )
      INTO actual_fact_set_sha256
      FROM grocery_publicationentry AS entry
     WHERE entry.revision_id = NEW.id;
    IF actual_fact_set_sha256 IS DISTINCT FROM NEW.typed_fact_set_sha256 THEN
        RAISE EXCEPTION 'publication typed fact-set hash does not match ordered entries'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$function$;

CREATE TRIGGER grocery_publicationrevision_seal_or_immutable
BEFORE UPDATE OR DELETE ON grocery_publicationrevision
FOR EACH ROW
EXECUTE FUNCTION grocery_publicationrevision_validate_seal();
"""


DROP_PUBLICATION_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS grocery_publicationrevision_seal_or_immutable
    ON grocery_publicationrevision;
DROP FUNCTION IF EXISTS grocery_publicationrevision_validate_seal();
DROP TRIGGER IF EXISTS grocery_publicationentry_immutable
    ON grocery_publicationentry;
DROP FUNCTION IF EXISTS grocery_publicationentry_reject_mutation();
DROP TRIGGER IF EXISTS grocery_publicationentry_validate
    ON grocery_publicationentry;
DROP FUNCTION IF EXISTS grocery_publicationentry_validate_insert();
DROP FUNCTION IF EXISTS grocery_publication_snapshot_fact_sha256(uuid);
DROP TRIGGER IF EXISTS grocery_publicationrevision_unsealed_insert
    ON grocery_publicationrevision;
DROP FUNCTION IF EXISTS grocery_publicationrevision_validate_insert();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("grocery", "0006_review_decision"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("RECENT_RETAIL", "Recent retail")],
                        default="RECENT_RETAIL",
                        max_length=32,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("RECENT_COMPARISON", "Recent comparison")],
                        default="RECENT_COMPARISON",
                        max_length=32,
                    ),
                ),
                ("parser_revision", models.CharField(max_length=64)),
                (
                    "fact_hash_version",
                    models.CharField(
                        default="recent-retail-fact-set-v1",
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "typed_fact_set_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "entry_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("source_effective_date_min", models.DateField()),
                ("source_effective_date_max", models.DateField()),
                (
                    "public_copy_revision",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator("^[a-z0-9][a-z0-9._-]{0,63}$")
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sealed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_revisions",
                        to="grocery.parserun",
                    ),
                ),
                (
                    "review_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_revisions",
                        to="grocery.reviewdecision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ordinal",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "fact_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="grocery.publicationrevision",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_entries",
                        to="grocery.retailpricesnapshot",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="publicationrevision",
            constraint=models.UniqueConstraint(
                fields=("channel", "typed_fact_set_sha256", "public_copy_revision"),
                name="grocery_publication_set_copy_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("channel", "RECENT_RETAIL")),
                name="grocery_publication_channel_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("mode", "RECENT_COMPARISON")),
                name="grocery_publication_mode_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("fact_hash_version", "recent-retail-fact-set-v1")),
                name="grocery_publication_hash_version_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("typed_fact_set_sha256__regex", "^[0-9a-f]{64}$")),
                name="grocery_publication_set_hash_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("entry_count__gt", 0)),
                name="grocery_publication_entry_count_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_effective_date_max__gte", models.F("source_effective_date_min"))
                ),
                name="grocery_publication_date_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("public_copy_revision__regex", "^[a-z0-9][a-z0-9._-]{0,63}$")),
                name="grocery_publication_copy_revision_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sealed_at__isnull", True),
                    ("sealed_at__gte", models.F("created_at")),
                    _connector="OR",
                ),
                name="grocery_publication_seal_time_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationentry",
            constraint=models.UniqueConstraint(
                fields=("revision", "ordinal"),
                name="grocery_publication_entry_ordinal_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationentry",
            constraint=models.UniqueConstraint(
                fields=("revision", "snapshot"),
                name="grocery_publication_entry_snapshot_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordinal__gt", 0)),
                name="grocery_publication_entry_ordinal_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("fact_sha256__regex", "^[0-9a-f]{64}$")),
                name="grocery_publication_entry_hash_valid",
            ),
        ),
        migrations.RunSQL(
            sql=PUBLICATION_TRIGGER_SQL,
            reverse_sql=DROP_PUBLICATION_TRIGGER_SQL,
        ),
    ]
