# Generated by Django 5.2.17 on 2026-08-30 04:04

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

PUBLICATION_ACTIVATION_TRIGGER_SQL = r"""
CREATE FUNCTION grocery_publicationchannel_guard_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    capability text := current_setting('grocery.publication_transition_id', true);
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'publication channels cannot be deleted'
            USING ERRCODE = '55000';
    END IF;
    IF capability IS NULL
       OR capability !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN
        RAISE EXCEPTION 'publication channel mutation requires transition capability'
            USING ERRCODE = '42501';
    END IF;

    IF TG_OP = 'INSERT' THEN
        IF NEW.channel IS DISTINCT FROM 'RECENT_RETAIL'
           OR NEW.current_revision_id IS NOT NULL
           OR NEW.version IS DISTINCT FROM 0::bigint THEN
            RAISE EXCEPTION 'publication channel bootstrap state is invalid'
                USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.channel IS DISTINCT FROM OLD.channel
       OR NEW.version IS DISTINCT FROM OLD.version + 1 THEN
        RAISE EXCEPTION 'publication channel version transition is invalid'
            USING ERRCODE = '23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1
          FROM grocery_publicationactivation AS activation
         WHERE activation.id::text = capability
           AND activation.channel_id = NEW.channel
           AND activation.sequence = NEW.version
           AND activation.previous_revision_id IS NOT DISTINCT FROM OLD.current_revision_id
           AND activation.target_revision_id IS NOT DISTINCT FROM NEW.current_revision_id
    ) THEN
        RAISE EXCEPTION 'publication channel transition has no matching activation'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$function$;

CREATE TRIGGER grocery_publicationchannel_guard
BEFORE INSERT OR UPDATE OR DELETE ON grocery_publicationchannel
FOR EACH ROW
EXECUTE FUNCTION grocery_publicationchannel_guard_mutation();

CREATE FUNCTION grocery_publicationactivation_validate_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    capability text := current_setting('grocery.publication_transition_id', true);
    channel_record grocery_publicationchannel%ROWTYPE;
BEGIN
    IF capability IS NULL OR capability IS DISTINCT FROM NEW.id::text THEN
        RAISE EXCEPTION 'publication activation insert requires matching transition capability'
            USING ERRCODE = '42501';
    END IF;
    IF NEW.channel_id IS DISTINCT FROM 'RECENT_RETAIL' THEN
        RAISE EXCEPTION 'publication activation channel is invalid'
            USING ERRCODE = '23514';
    END IF;

    SELECT * INTO channel_record
      FROM grocery_publicationchannel
     WHERE channel = NEW.channel_id
       FOR SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'publication activation channel does not exist'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.sequence IS DISTINCT FROM channel_record.version + 1
       OR NEW.previous_revision_id
          IS DISTINCT FROM channel_record.current_revision_id THEN
        RAISE EXCEPTION 'publication activation does not match the current pointer and sequence'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.operation = 'WITHDRAW' THEN
        IF NEW.target_revision_id IS NOT NULL
           OR NEW.previous_revision_id IS NULL THEN
            RAISE EXCEPTION 'publication withdrawal previous and target state is invalid'
                USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
    END IF;
    IF NEW.operation NOT IN ('ACTIVATE', 'ROLLBACK')
       OR NEW.target_revision_id IS NULL
       OR NEW.target_revision_id IS NOT DISTINCT FROM NEW.previous_revision_id THEN
        RAISE EXCEPTION 'publication activation previous and target state is invalid'
            USING ERRCODE = '23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1
          FROM grocery_publicationrevision AS revision
          JOIN grocery_reviewdecision AS decision
            ON decision.id = revision.review_decision_id
         WHERE revision.id = NEW.target_revision_id
           AND revision.channel = NEW.channel_id
           AND revision.sealed_at IS NOT NULL
           AND decision.decision = 'APPROVE'
           AND NOT EXISTS (
               SELECT 1
                 FROM grocery_reviewdecision AS replacement
                WHERE replacement.supersedes_id = decision.id
           )
    ) THEN
        RAISE EXCEPTION 'publication target is not a sealed approved revision'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.operation = 'ROLLBACK'
       AND NOT EXISTS (
           SELECT 1
             FROM grocery_publicationactivation AS prior
            WHERE prior.channel_id = NEW.channel_id
              AND prior.sequence < NEW.sequence
              AND prior.operation IN ('ACTIVATE', 'ROLLBACK')
              AND prior.target_revision_id = NEW.target_revision_id
       ) THEN
        RAISE EXCEPTION 'publication rollback target was not previously current'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$function$;

CREATE TRIGGER grocery_publicationactivation_validate
BEFORE INSERT ON grocery_publicationactivation
FOR EACH ROW
EXECUTE FUNCTION grocery_publicationactivation_validate_insert();

CREATE FUNCTION grocery_publicationactivation_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    RAISE EXCEPTION 'grocery_publicationactivation rows are append-only'
        USING ERRCODE = '55000';
END;
$function$;

CREATE TRIGGER grocery_publicationactivation_immutable
BEFORE UPDATE OR DELETE ON grocery_publicationactivation
FOR EACH ROW
EXECUTE FUNCTION grocery_publicationactivation_reject_mutation();

CREATE FUNCTION grocery_publication_assert_channel_state(channel_key varchar)
RETURNS void
LANGUAGE plpgsql
AS $function$
DECLARE
    channel_record grocery_publicationchannel%ROWTYPE;
    activation_count bigint;
    maximum_sequence bigint;
    latest_target uuid;
BEGIN
    SELECT * INTO channel_record
      FROM grocery_publicationchannel
     WHERE channel = channel_key;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'publication channel state is missing'
            USING ERRCODE = '23514';
    END IF;

    SELECT count(*), coalesce(max(sequence), 0)
      INTO activation_count, maximum_sequence
      FROM grocery_publicationactivation
     WHERE channel_id = channel_key;
    IF activation_count = 0 THEN
        IF channel_record.version IS DISTINCT FROM 0::bigint
           OR channel_record.current_revision_id IS NOT NULL THEN
            RAISE EXCEPTION 'empty publication channel state is inconsistent'
                USING ERRCODE = '23514';
        END IF;
        RETURN;
    END IF;

    SELECT target_revision_id INTO latest_target
      FROM grocery_publicationactivation
     WHERE channel_id = channel_key
     ORDER BY sequence DESC
     LIMIT 1;
    IF channel_record.version IS DISTINCT FROM maximum_sequence
       OR maximum_sequence IS DISTINCT FROM activation_count
       OR channel_record.current_revision_id IS DISTINCT FROM latest_target THEN
        RAISE EXCEPTION 'publication activation and current pointer are inconsistent'
            USING ERRCODE = '23514';
    END IF;
    IF EXISTS (
        SELECT 1
          FROM grocery_publicationactivation AS current_event
          LEFT JOIN grocery_publicationactivation AS previous_event
            ON previous_event.channel_id = current_event.channel_id
           AND previous_event.sequence = current_event.sequence - 1
         WHERE current_event.channel_id = channel_key
           AND (
               (current_event.sequence = 1 AND current_event.previous_revision_id IS NOT NULL)
               OR (
                   current_event.sequence > 1
                   AND (
                       previous_event.id IS NULL
                       OR current_event.previous_revision_id
                          IS DISTINCT FROM previous_event.target_revision_id
                   )
               )
           )
    ) THEN
        RAISE EXCEPTION 'publication activation history is not contiguous'
            USING ERRCODE = '23514';
    END IF;
END;
$function$;

CREATE FUNCTION grocery_publicationactivation_deferred_consistency()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    PERFORM grocery_publication_assert_channel_state(NEW.channel_id);
    RETURN NULL;
END;
$function$;

CREATE CONSTRAINT TRIGGER grocery_publicationactivation_state_consistent
AFTER INSERT ON grocery_publicationactivation
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION grocery_publicationactivation_deferred_consistency();

CREATE FUNCTION grocery_publicationchannel_deferred_consistency()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    PERFORM grocery_publication_assert_channel_state(NEW.channel);
    RETURN NULL;
END;
$function$;

CREATE CONSTRAINT TRIGGER grocery_publicationchannel_state_consistent
AFTER INSERT OR UPDATE ON grocery_publicationchannel
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION grocery_publicationchannel_deferred_consistency();
"""


DROP_PUBLICATION_ACTIVATION_TRIGGER_SQL = r"""
DROP TRIGGER IF EXISTS grocery_publicationchannel_state_consistent
    ON grocery_publicationchannel;
DROP FUNCTION IF EXISTS grocery_publicationchannel_deferred_consistency();
DROP TRIGGER IF EXISTS grocery_publicationactivation_state_consistent
    ON grocery_publicationactivation;
DROP FUNCTION IF EXISTS grocery_publicationactivation_deferred_consistency();
DROP FUNCTION IF EXISTS grocery_publication_assert_channel_state(varchar);
DROP TRIGGER IF EXISTS grocery_publicationactivation_immutable
    ON grocery_publicationactivation;
DROP FUNCTION IF EXISTS grocery_publicationactivation_reject_mutation();
DROP TRIGGER IF EXISTS grocery_publicationactivation_validate
    ON grocery_publicationactivation;
DROP FUNCTION IF EXISTS grocery_publicationactivation_validate_insert();
DROP TRIGGER IF EXISTS grocery_publicationchannel_guard
    ON grocery_publicationchannel;
DROP FUNCTION IF EXISTS grocery_publicationchannel_guard_mutation();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("grocery", "0007_publication_revision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationChannel",
            fields=[
                (
                    "channel",
                    models.CharField(
                        choices=[("RECENT_RETAIL", "Recent retail")],
                        default="RECENT_RETAIL",
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=0, editable=False)),
                (
                    "current_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_for_channels",
                        to="grocery.publicationrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationActivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("ACTIVATE", "Activate"),
                            ("ROLLBACK", "Rollback"),
                            ("WITHDRAW", "Withdraw"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        max_length=64,
                        validators=[django.core.validators.RegexValidator("^[A-Z][A-Z0-9_]*$")],
                    ),
                ),
                (
                    "acceptance_evidence_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "previous_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="previous_publication_activations",
                        to="grocery.publicationrevision",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grocery_publication_activations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_publication_activations",
                        to="grocery.publicationrevision",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activations",
                        to="grocery.publicationchannel",
                    ),
                ),
            ],
            options={
                "permissions": [("publish_publication", "Can transition a grocery publication")],
            },
        ),
        migrations.AddConstraint(
            model_name="publicationchannel",
            constraint=models.CheckConstraint(
                condition=models.Q(("channel", "RECENT_RETAIL")),
                name="grocery_publication_pointer_channel_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationchannel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("current_revision__isnull", True), ("version", 0)),
                    ("version__gt", 0),
                    _connector="OR",
                ),
                name="grocery_publication_pointer_initial_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationactivation",
            constraint=models.CheckConstraint(
                condition=models.Q(("channel_id", "RECENT_RETAIL")),
                name="grocery_activation_channel_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationactivation",
            constraint=models.CheckConstraint(
                condition=models.Q(("operation__in", ("ACTIVATE", "ROLLBACK", "WITHDRAW"))),
                name="grocery_activation_operation_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationactivation",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gt", 0)), name="grocery_activation_sequence_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationactivation",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason_code__regex", "^[A-Z][A-Z0-9_]*$")),
                name="grocery_activation_reason_code_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationactivation",
            constraint=models.CheckConstraint(
                condition=models.Q(("acceptance_evidence_sha256__regex", "^[0-9a-f]{64}$")),
                name="grocery_activation_evidence_hash_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationactivation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("operation__in", ("ACTIVATE", "ROLLBACK")),
                        ("target_revision__isnull", False),
                    ),
                    models.Q(("operation", "WITHDRAW"), ("target_revision__isnull", True)),
                    _connector="OR",
                ),
                name="grocery_activation_target_shape_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationactivation",
            constraint=models.UniqueConstraint(
                fields=("channel", "sequence"), name="grocery_activation_channel_sequence_uniq"
            ),
        ),
        migrations.RunSQL(
            sql=PUBLICATION_ACTIVATION_TRIGGER_SQL,
            reverse_sql=DROP_PUBLICATION_ACTIVATION_TRIGGER_SQL,
        ),
    ]
