# Generated by Django 5.2.17 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grocery", "0008_publication_activation"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceconfiguration",
            name="schedule_execution_mode",
            field=models.CharField(
                choices=[("PLATFORM_SINGLETON", "Platform-owned singleton job")],
                default="PLATFORM_SINGLETON",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="sourceconfiguration",
            name="schedule_interval_hours",
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddConstraint(
            model_name="sourceconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(schedule_execution_mode="PLATFORM_SINGLETON"),
                name="grocery_source_schedule_mode_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    schedule_interval_hours__gt=0,
                    schedule_interval_hours__lte=24,
                ),
                name="grocery_source_schedule_interval_valid",
            ),
        ),
    ]
