# Generated by Django 5.2.17 on 2026-08-30 08:12

import datetime
import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

SOURCE_CONFIGURATION_ID = uuid.UUID("e7c14e61-8c56-5758-b1ea-1ea87ea60a41")
CORRECTION_ID = uuid.uuid5(
    uuid.NAMESPACE_URL,
    "https://www.data.go.kr/data/15156063/openapi.do"
    "#kamis-15156063-recent-comparison-v1/gate-timestamp-correction-v1",
)
ORIGINAL_TIMESTAMP = datetime.datetime(2026, 8, 29, 15, 0, tzinfo=datetime.UTC)
EFFECTIVE_TIMESTAMP = datetime.datetime(2026, 8, 30, 2, 23, 44, tzinfo=datetime.UTC)
EVIDENCE_COMMIT_SHA = "d23e5707e1fc3bf6e032d459b149b946b0451e00"


def append_legacy_gate_timestamp_correction(apps, schema_editor):
    del schema_editor
    SourceConfiguration = apps.get_model("grocery", "SourceConfiguration")
    FetchAttempt = apps.get_model("grocery", "FetchAttempt")
    Correction = apps.get_model(
        "grocery",
        "SourceConfigurationGateTimestampCorrection",
    )

    source = SourceConfiguration.objects.filter(pk=SOURCE_CONFIGURATION_ID).first()
    if source is None:
        return
    if (
        source.dataset_id != "15156063"
        or source.configuration_revision != "kamis-15156063-recent-comparison-v1"
    ):
        raise RuntimeError("The source gate timestamp correction target is invalid.")

    existing = Correction.objects.filter(source_configuration_id=source.pk).first()
    if existing is not None:
        raise RuntimeError("The source gate timestamp correction already exists.")
    if (
        source.state_changed_at == EFFECTIVE_TIMESTAMP
        and source.rights_confirmed_at == EFFECTIVE_TIMESTAMP
    ):
        return
    if (
        source.state_changed_at != ORIGINAL_TIMESTAMP
        or source.rights_confirmed_at != ORIGINAL_TIMESTAMP
    ):
        raise RuntimeError("The source gate timestamp correction originals do not match.")
    first_fetch = (
        FetchAttempt.objects.filter(source_configuration_id=source.pk)
        .order_by("started_at", "id")
        .first()
    )
    if (
        first_fetch is None
        or source.created_at <= EFFECTIVE_TIMESTAMP
        or first_fetch.started_at <= EFFECTIVE_TIMESTAMP
    ):
        raise RuntimeError("The source gate timestamp correction chronology is invalid.")

    Correction.objects.create(
        id=CORRECTION_ID,
        source_configuration_id=source.pk,
        original_state_changed_at=ORIGINAL_TIMESTAMP,
        original_rights_confirmed_at=ORIGINAL_TIMESTAMP,
        effective_gate_decision_recorded_at=EFFECTIVE_TIMESTAMP,
        timestamp_basis="DURABLE_SOURCE_GATE_COMMIT",
        evidence_commit_sha=EVIDENCE_COMMIT_SHA,
        reason_code="GATE_TIMESTAMP_DATE_PRECISION_CORRECTED",
    )


def remove_legacy_gate_timestamp_correction(apps, schema_editor):
    del schema_editor
    Correction = apps.get_model(
        "grocery",
        "SourceConfigurationGateTimestampCorrection",
    )
    Correction.objects.filter(pk=CORRECTION_ID).delete()


IMMUTABLE_CORRECTION_SQL = r"""
CREATE FUNCTION grocery_gate_time_validate_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    source_record grocery_sourceconfiguration%ROWTYPE;
    first_fetch_at timestamptz;
BEGIN
    SELECT * INTO source_record
      FROM grocery_sourceconfiguration
     WHERE id = NEW.source_configuration_id
       FOR SHARE;
    IF NOT FOUND
       OR source_record.dataset_id IS DISTINCT FROM '15156063'
       OR source_record.configuration_revision
          IS DISTINCT FROM 'kamis-15156063-recent-comparison-v1'
       OR source_record.state_changed_at IS DISTINCT FROM NEW.original_state_changed_at
       OR source_record.rights_confirmed_at IS DISTINCT FROM NEW.original_rights_confirmed_at THEN
        RAISE EXCEPTION 'source gate timestamp correction base row is invalid'
            USING ERRCODE = '23514';
    END IF;

    SELECT min(started_at) INTO first_fetch_at
      FROM grocery_fetchattempt
     WHERE source_configuration_id = NEW.source_configuration_id;
    IF first_fetch_at IS NULL
       OR NEW.effective_gate_decision_recorded_at >= first_fetch_at THEN
        RAISE EXCEPTION 'source gate timestamp correction chronology is invalid'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$function$;

CREATE TRIGGER grocery_gate_time_validate
BEFORE INSERT ON grocery_sourceconfigurationgatetimestampcorrection
FOR EACH ROW
EXECUTE FUNCTION grocery_gate_time_validate_insert();

CREATE FUNCTION grocery_gate_time_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    RAISE EXCEPTION 'source gate timestamp corrections are append-only'
        USING ERRCODE = '55000';
END;
$function$;

CREATE TRIGGER grocery_gate_time_immutable
BEFORE UPDATE OR DELETE ON grocery_sourceconfigurationgatetimestampcorrection
FOR EACH ROW
EXECUTE FUNCTION grocery_gate_time_reject_mutation();

CREATE FUNCTION grocery_review_gate_time_validate_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    source_record grocery_sourceconfiguration%ROWTYPE;
    correction_record grocery_sourceconfigurationgatetimestampcorrection%ROWTYPE;
    effective_state_at timestamptz;
    effective_rights_at timestamptz;
BEGIN
    SELECT * INTO source_record
      FROM grocery_sourceconfiguration
     WHERE id = NEW.source_configuration_id
       FOR SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'review source configuration does not exist'
            USING ERRCODE = '23503';
    END IF;

    SELECT * INTO correction_record
      FROM grocery_sourceconfigurationgatetimestampcorrection
     WHERE source_configuration_id = NEW.source_configuration_id;
    IF FOUND THEN
        IF correction_record.original_state_changed_at
              IS DISTINCT FROM source_record.state_changed_at
           OR correction_record.original_rights_confirmed_at
              IS DISTINCT FROM source_record.rights_confirmed_at THEN
            RAISE EXCEPTION 'review source gate timestamp correction is invalid'
                USING ERRCODE = '23514';
        END IF;
        effective_state_at := correction_record.effective_gate_decision_recorded_at;
        effective_rights_at := correction_record.effective_gate_decision_recorded_at;
    ELSE
        effective_state_at := source_record.state_changed_at;
        effective_rights_at := source_record.rights_confirmed_at;
    END IF;

    IF effective_rights_at IS NULL
       OR effective_state_at > NEW.decided_at
       OR effective_rights_at > NEW.decided_at THEN
        RAISE EXCEPTION 'review precedes effective source gate decision'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$function$;

CREATE TRIGGER grocery_review_gate_time_validate
BEFORE INSERT ON grocery_reviewdecision
FOR EACH ROW
EXECUTE FUNCTION grocery_review_gate_time_validate_insert();
"""

DROP_IMMUTABLE_CORRECTION_SQL = r"""
DROP TRIGGER IF EXISTS grocery_review_gate_time_validate
    ON grocery_reviewdecision;
DROP FUNCTION IF EXISTS grocery_review_gate_time_validate_insert();
DROP TRIGGER IF EXISTS grocery_gate_time_immutable
    ON grocery_sourceconfigurationgatetimestampcorrection;
DROP FUNCTION IF EXISTS grocery_gate_time_reject_mutation();
DROP TRIGGER IF EXISTS grocery_gate_time_validate
    ON grocery_sourceconfigurationgatetimestampcorrection;
DROP FUNCTION IF EXISTS grocery_gate_time_validate_insert();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("grocery", "0009_source_configuration_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceConfigurationGateTimestampCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_state_changed_at", models.DateTimeField()),
                ("original_rights_confirmed_at", models.DateTimeField()),
                ("effective_gate_decision_recorded_at", models.DateTimeField()),
                (
                    "timestamp_basis",
                    models.CharField(
                        choices=[
                            (
                                "DURABLE_SOURCE_GATE_COMMIT",
                                "Durable source-gate commit recorded-at upper bound",
                            )
                        ],
                        default="DURABLE_SOURCE_GATE_COMMIT",
                        max_length=40,
                    ),
                ),
                (
                    "evidence_commit_sha",
                    models.CharField(
                        default="d23e5707e1fc3bf6e032d459b149b946b0451e00",
                        max_length=40,
                        validators=[django.core.validators.RegexValidator("^[0-9a-f]{40}$")],
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            (
                                "GATE_TIMESTAMP_DATE_PRECISION_CORRECTED",
                                "Gate timestamp date precision corrected",
                            )
                        ],
                        default="GATE_TIMESTAMP_DATE_PRECISION_CORRECTED",
                        max_length=48,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_configuration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gate_timestamp_correction",
                        to="grocery.sourceconfiguration",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "source_configuration_id",
                                uuid.UUID("e7c14e61-8c56-5758-b1ea-1ea87ea60a41"),
                            )
                        ),
                        name="grocery_gate_time_source_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "original_rights_confirmed_at",
                                datetime.datetime(2026, 8, 29, 15, 0, tzinfo=datetime.UTC),
                            ),
                            (
                                "original_state_changed_at",
                                datetime.datetime(2026, 8, 29, 15, 0, tzinfo=datetime.UTC),
                            ),
                        ),
                        name="grocery_gate_time_original_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("timestamp_basis", "DURABLE_SOURCE_GATE_COMMIT")),
                        name="grocery_gate_time_basis_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reason_code", "GATE_TIMESTAMP_DATE_PRECISION_CORRECTED")
                        ),
                        name="grocery_gate_time_reason_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("evidence_commit_sha", "d23e5707e1fc3bf6e032d459b149b946b0451e00")
                        ),
                        name="grocery_gate_time_commit_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "effective_gate_decision_recorded_at",
                                datetime.datetime(2026, 8, 30, 2, 23, 44, tzinfo=datetime.UTC),
                            )
                        ),
                        name="grocery_gate_time_effective_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "effective_gate_decision_recorded_at__gt",
                                models.F("original_state_changed_at"),
                            ),
                            (
                                "effective_gate_decision_recorded_at__gt",
                                models.F("original_rights_confirmed_at"),
                            ),
                        ),
                        name="grocery_gate_time_chronology_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            append_legacy_gate_timestamp_correction,
            remove_legacy_gate_timestamp_correction,
        ),
        migrations.RunSQL(
            sql=IMMUTABLE_CORRECTION_SQL,
            reverse_sql=DROP_IMMUTABLE_CORRECTION_SQL,
        ),
    ]
