# Generated by Django 5.2.17 on 2026-08-31 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grocery", "0010_source_gate_timestamp_correction"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sourceconfiguration",
            name="grocery_source_publication_mode_valid",
        ),
        migrations.RemoveConstraint(
            model_name="sourceconfiguration",
            name="grocery_source_schedule_interval_valid",
        ),
        migrations.AddField(
            model_name="fetchattempt",
            name="request_scope_sha256",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a lowercase 64-character SHA-256 digest.",
                        regex="^[0-9a-f]{64}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="reviewdecision",
            name="approved_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RECENT_COMPARISON", "Recent comparison"),
                    ("CURRENT_ONLY", "Current only"),
                    ("STATIC_MONTHLY_FILE", "Static monthly file"),
                    ("HISTORICAL_MONTHLY", "Historical monthly retail"),
                    ("HISTORICAL_REGIONAL", "Historical regional retail"),
                    ("HISTORICAL_MARKET", "Historical market retail"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="sourceconfiguration",
            name="publication_mode",
            field=models.CharField(
                choices=[
                    ("RECENT_COMPARISON", "Recent comparison"),
                    ("CURRENT_ONLY", "Current only"),
                    ("STATIC_MONTHLY_FILE", "Static monthly file"),
                    ("HISTORICAL_MONTHLY", "Historical monthly retail"),
                    ("HISTORICAL_REGIONAL", "Historical regional retail"),
                    ("HISTORICAL_MARKET", "Historical market retail"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="fetchattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("request_scope_sha256", ""),
                    ("request_scope_sha256__regex", "^[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="grocery_fetch_scope_hash_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "publication_mode__in",
                        (
                            "RECENT_COMPARISON",
                            "CURRENT_ONLY",
                            "STATIC_MONTHLY_FILE",
                            "HISTORICAL_MONTHLY",
                            "HISTORICAL_REGIONAL",
                            "HISTORICAL_MARKET",
                        ),
                    )
                ),
                name="grocery_source_publication_mode_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("schedule_interval_hours__gt", 0), ("schedule_interval_hours__lte", 168)
                ),
                name="grocery_source_schedule_interval_valid",
            ),
        ),
    ]
