# Generated by Django 5.2.17 on 2026-08-31 04:14

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grocery", "0011_historical_source_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalRetailSeriesKey",
            fields=[
                (
                    "recent_series",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="historical_identity",
                        serialize=False,
                        to="grocery.priceserieskey",
                    ),
                ),
                (
                    "series_identity_sha256",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("cross_source_evidence_revision", models.CharField(max_length=128)),
                (
                    "code_manifest_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("series_identity_sha256__regex", "^[0-9a-f]{64}$")),
                        name="grocery_history_series_hash_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("code_manifest_sha256__regex", "^[0-9a-f]{64}$")),
                        name="grocery_history_series_manifest_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cross_source_evidence_revision", ""), _negated=True),
                        name="grocery_history_series_evidence_nonempty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RetailRegionKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "region_code",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[django.core.validators.RegexValidator("^[0-9]+$")],
                    ),
                ),
                ("region_name", models.CharField(max_length=200)),
                ("identity_evidence_revision", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("region_code__regex", "^[0-9]+$")),
                        name="grocery_region_code_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("region_name", ""), _negated=True),
                            models.Q(("identity_evidence_revision", ""), _negated=True),
                        ),
                        name="grocery_region_identity_complete",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RetailMarketKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "market_code",
                    models.CharField(
                        max_length=32,
                        validators=[django.core.validators.RegexValidator("^[0-9]+$")],
                    ),
                ),
                ("market_name", models.CharField(max_length=200)),
                ("identity_evidence_revision", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markets",
                        to="grocery.retailregionkey",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("region", "market_code"), name="grocery_market_region_code_uniq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("market_code__regex", "^[0-9]+$")),
                        name="grocery_market_code_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("market_name", ""), _negated=True),
                            models.Q(("identity_evidence_revision", ""), _negated=True),
                        ),
                        name="grocery_market_identity_complete",
                    ),
                ],
            },
        ),
    ]
