# Generated by Django 5.2.17 on 2026-08-31 04:15

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grocery", "0012_historical_source_identities"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSourceCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly regional retail"),
                            ("REGIONAL_DAILY", "Regional daily retail"),
                            ("MARKET_DAILY", "Market daily retail"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("VALIDATED", "Validated"),
                            ("FAILED", "Failed"),
                        ],
                        default="STARTED",
                        max_length=16,
                    ),
                ),
                (
                    "code_manifest_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "partition_manifest_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "expected_part_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "month_min",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator("^[0-9]{4}(0[1-9]|1[0-2])$")
                        ],
                    ),
                ),
                (
                    "month_max",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator("^[0-9]{4}(0[1-9]|1[0-2])$")
                        ],
                    ),
                ),
                ("date_min", models.DateField(blank=True, null=True)),
                ("date_max", models.DateField(blank=True, null=True)),
                ("accepted_row_count", models.PositiveIntegerField(default=0)),
                ("out_of_scope_row_count", models.PositiveIntegerField(default=0)),
                ("quarantined_row_count", models.PositiveIntegerField(default=0)),
                (
                    "result_sha256",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        validators=[django.core.validators.RegexValidator("^[A-Z][A-Z0-9_]*$")],
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historical_collections",
                        to="grocery.sourceconfiguration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalSourceCollectionPart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ordinal",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "partition_scope_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("fact_count", models.PositiveIntegerField()),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parts",
                        to="grocery.historicalsourcecollection",
                    ),
                ),
                (
                    "parse_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historical_collection_part",
                        to="grocery.parserun",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="historicalsourcecollection",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ("MONTHLY", "REGIONAL_DAILY", "MARKET_DAILY"))),
                name="grocery_history_collection_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalsourcecollection",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ("STARTED", "VALIDATED", "FAILED"))),
                name="grocery_history_collection_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalsourcecollection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("code_manifest_sha256__regex", "^[0-9a-f]{64}$"),
                    ("partition_manifest_sha256__regex", "^[0-9a-f]{64}$"),
                ),
                name="grocery_history_collection_hashes_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalsourcecollection",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_part_count__gt", 0)),
                name="grocery_history_collection_parts_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalsourcecollection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("date_max__isnull", True),
                        ("date_min__isnull", True),
                        ("kind", "MONTHLY"),
                        ("month_max__regex", "^[0-9]{4}(0[1-9]|1[0-2])$"),
                        ("month_min__regex", "^[0-9]{4}(0[1-9]|1[0-2])$"),
                    ),
                    models.Q(
                        ("kind__in", ("REGIONAL_DAILY", "MARKET_DAILY")),
                        ("month_max", ""),
                        ("month_min", ""),
                        ("date_max__isnull", False),
                        ("date_min__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="grocery_history_collection_window_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalsourcecollection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(("kind", "MONTHLY"), ("month_max__gte", models.F("month_min"))),
                        models.Q(("kind", "MONTHLY"), _negated=True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("date_max__gte", models.F("date_min")),
                        ("date_min__isnull", True),
                        _connector="OR",
                    ),
                ),
                name="grocery_history_collection_window_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalsourcecollection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("result_sha256", ""),
                    ("result_sha256__regex", "^[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="grocery_history_collection_result_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalsourcecollection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", True),
                        ("failure_code", ""),
                        ("result_sha256", ""),
                        ("state", "STARTED"),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("failure_code", ""),
                        ("quarantined_row_count", 0),
                        ("state", "VALIDATED"),
                        models.Q(("result_sha256", ""), _negated=True),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("result_sha256", ""),
                        ("state", "FAILED"),
                        models.Q(("failure_code", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="grocery_history_collection_outcome_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalsourcecollectionpart",
            constraint=models.UniqueConstraint(
                fields=("collection", "ordinal"), name="grocery_history_part_ordinal_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalsourcecollectionpart",
            constraint=models.UniqueConstraint(
                fields=("collection", "partition_scope_sha256"),
                name="grocery_history_part_scope_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalsourcecollectionpart",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordinal__gt", 0)), name="grocery_history_part_ordinal_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalsourcecollectionpart",
            constraint=models.CheckConstraint(
                condition=models.Q(("partition_scope_sha256__regex", "^[0-9a-f]{64}$")),
                name="grocery_history_part_scope_valid",
            ),
        ),
    ]
