# Generated by Django 5.2.17 on 2026-08-31 04:24

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grocery", "0014_historical_monthly_facts"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMarketRetailPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("KRW", "South Korean won")], default="KRW", max_length=3
                    ),
                ),
                (
                    "source_row_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("source_contract_revision", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("survey_date", models.DateField()),
                (
                    "provider_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                    ),
                ),
                ("source_recorded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="grocery.historicalsourcecollection",
                    ),
                ),
                (
                    "collection_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="grocery.historicalsourcecollectionpart",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="grocery.retailmarketkey"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="grocery.retailregionkey"
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="grocery.historicalretailserieskey",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("collection", "series", "region", "market", "survey_date"),
                        name="grocery_market_series_region_market_date_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider_price__gt", 0)),
                        name="grocery_market_price_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency", "KRW")), name="grocery_market_currency"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_row_sha256__regex", "^[0-9a-f]{64}$")),
                        name="grocery_market_row_hash_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyRegionalRetailPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("KRW", "South Korean won")], default="KRW", max_length=3
                    ),
                ),
                (
                    "source_row_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase 64-character SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("source_contract_revision", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("survey_date", models.DateField()),
                (
                    "provider_mean",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                    ),
                ),
                (
                    "provider_low",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                    ),
                ),
                (
                    "provider_high",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("1"))],
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="grocery.historicalsourcecollection",
                    ),
                ),
                (
                    "collection_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="grocery.historicalsourcecollectionpart",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="grocery.retailregionkey"
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="grocery.historicalretailserieskey",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("collection", "series", "region", "survey_date"),
                        name="grocery_regional_series_region_date_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("provider_low__gt", 0),
                            ("provider_mean__gte", models.F("provider_low")),
                            ("provider_high__gte", models.F("provider_mean")),
                        ),
                        name="grocery_regional_price_range_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency", "KRW")), name="grocery_regional_currency"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_row_sha256__regex", "^[0-9a-f]{64}$")),
                        name="grocery_regional_row_hash_valid",
                    ),
                ],
            },
        ),
    ]
