# Generated by Django 5.2.17 on 2026-08-31 04:31

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0016_historical_collection_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRetailPublicationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_manifest_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a lowercase 64-character SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('compatibility_report_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a lowercase 64-character SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('fact_hash_version', models.CharField(default='historical-retail-bundle-v1', editable=False, max_length=64)),
                ('typed_fact_set_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a lowercase 64-character SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('series_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('monthly_fact_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('regional_fact_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('market_fact_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('month_min', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{4}(0[1-9]|1[0-2])$')])),
                ('month_max', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{4}(0[1-9]|1[0-2])$')])),
                ('date_min', models.DateField()),
                ('date_max', models.DateField()),
                ('public_copy_revision', models.CharField(default='ko-v4', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('market_review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_publication_revisions', to='grocery.historicalcollectionreviewdecision')),
                ('monthly_review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_publication_revisions', to='grocery.historicalcollectionreviewdecision')),
                ('regional_review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regional_publication_revisions', to='grocery.historicalcollectionreviewdecision')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('typed_fact_set_sha256', 'public_copy_revision'), name='grocery_history_publication_set_copy_uniq'), models.CheckConstraint(condition=models.Q(('code_manifest_sha256__regex', '^[0-9a-f]{64}$'), ('compatibility_report_sha256__regex', '^[0-9a-f]{64}$'), ('typed_fact_set_sha256__regex', '^[0-9a-f]{64}$')), name='grocery_history_publication_hashes_valid'), models.CheckConstraint(condition=models.Q(('fact_hash_version', 'historical-retail-bundle-v1')), name='grocery_history_publication_hash_version'), models.CheckConstraint(condition=models.Q(('series_count__gt', 0), ('monthly_fact_count__gt', 0), ('regional_fact_count__gt', 0), ('market_fact_count__gt', 0)), name='grocery_history_publication_counts_positive'), models.CheckConstraint(condition=models.Q(('month_min__regex', '^[0-9]{4}(0[1-9]|1[0-2])$'), ('month_max__regex', '^[0-9]{4}(0[1-9]|1[0-2])$'), ('month_max__gte', models.F('month_min'))), name='grocery_history_publication_months_valid'), models.CheckConstraint(condition=models.Q(('date_max__gte', models.F('date_min'))), name='grocery_history_publication_dates_valid'), models.CheckConstraint(condition=models.Q(('public_copy_revision', 'ko-v4')), name='grocery_history_publication_copy_valid'), models.CheckConstraint(condition=models.Q(('sealed_at__isnull', True), ('sealed_at__gte', models.F('created_at')), _connector='OR'), name='grocery_history_publication_seal_time')],
            },
        ),
    ]
