# Generated by Django 5.2.17 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grocery", "0027_allow_historical_last_known_good_rollback"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sourceconfiguration",
            name="grocery_source_schedule_interval_valid",
        ),
        migrations.AddConstraint(
            model_name="sourceconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("schedule_interval_hours__gt", 0),
                    models.Q(
                        ("publication_mode", "HISTORICAL_MONTHLY"),
                        ("schedule_interval_hours__lte", 168),
                    )
                    | (
                        ~models.Q(("publication_mode", "HISTORICAL_MONTHLY"))
                        & models.Q(("schedule_interval_hours__lte", 24))
                    ),
                ),
                name="grocery_source_schedule_interval_valid",
            ),
        ),
    ]
